import { Link } from "react-router-dom";

export default function PrivacyPolicyPage() {
  return (
    <div className="soft-enter">
      {/* Hero Banner */}
      <section className="brand-gradient overflow-hidden text-white">
        <div className="section-shell flex items-center justify-center" style={{ minHeight: '260px' }}>
          <div className="text-center w-full">
            <h1 className="text-3xl font-bold sm:text-4xl">PRIVACY POLICY</h1>
            <p className="mt-4 text-sm text-slate-100/90">
              <Link to="/" className="hover:text-white">
                Home
              </Link>
              {" »  "}
              <span className="text-slate-100">Privacy Policy</span>
            </p>
          </div>
        </div>
      </section>

      {/* Content */}
      <section className="section-shell py-14">
        <div className="prose prose-sm max-w-3xl mx-auto text-slate-700">
          <p className="text-sm text-slate-600 mb-8">Effective date: 2024-03-09</p>

          <h2 className="text-2xl font-bold text-slate-900 mb-6">1. Introduction</h2>
          <p className="mb-4">
            Welcome to <span className="font-semibold">PickAll Movers</span>.
          </p>
          <p className="mb-6">
            <span className="font-semibold">PickAll Movers</span> ("us", "we", or "our") operates <span className="font-semibold">pickall.in</span> (hereinafter referred to as "<span className="font-semibold">Service</span>").
          </p>
          <p className="mb-6">
            Our Privacy Policy governs your visit to <span className="font-semibold">pickall.in</span>, and explains how we collect, safeguard and disclose information that results from your use of our Service.
          </p>
          <p className="mb-6">
            We use your data to provide and improve Service. By using Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.
          </p>
          <p className="mb-6">
            Our Terms and Conditions ("<span className="font-semibold">Terms</span>") govern all use of our Service and together with the Privacy Policy constitutes your agreement with us ("<span className="font-semibold">agreement</span>").
          </p>

          <h2 className="text-2xl font-bold text-slate-900 mb-6 mt-10">2. Definitions</h2>
          <div className="space-y-4 mb-8">
            <div>
              <p className="font-semibold">SERVICE</p>
              <p>The PickAll Movers website and all related services, features, and functionality.</p>
            </div>
            <div>
              <p className="font-semibold">PERSONAL DATA</p>
              <p>Any information relating to an identified or identifiable natural person ("data subject"); an identifiable natural person is one who can be identified, directly or indirectly, in particular by reference to an identifier such as a name, an identification number, location data, an online identifier or to one or more factors specific to the physical, physiological, genetic, mental, economic, cultural or social identity of that natural person.</p>
            </div>
            <div>
              <p className="font-semibold">USAGE DATA</p>
              <p>Information collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit).</p>
            </div>
          </div>

          <h2 className="text-2xl font-bold text-slate-900 mb-6 mt-10">3. Information Collection and Use</h2>
          <p className="mb-6">
            We collect several different types of information for various purposes to provide and improve our Service to you.
          </p>
          
          <h3 className="text-lg font-bold text-slate-900 mb-4">Types of Data Collected:</h3>
          <div className="space-y-4 mb-8">
            <div>
              <p className="font-semibold">Personal Data</p>
              <p>While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). This may include, but is not limited to:</p>
              <ul className="list-disc pl-6 mt-2 space-y-1">
                <li>Email address</li>
                <li>First name and last name</li>
                <li>Phone number</li>
                <li>Address, State, Province, ZIP/Postal code, City</li>
                <li>Cookies and Usage Data</li>
              </ul>
            </div>
            <div>
              <p className="font-semibold">Usage Data</p>
              <p>We may also collect information on how the Service is accessed and used ("Usage Data"). This may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages you visit, the time and date of your visit, the time spent on those pages, and other diagnostic data.</p>
            </div>
          </div>

          <h2 className="text-2xl font-bold text-slate-900 mb-6 mt-10">4. Use of Data</h2>
          <p className="mb-4">PickAll uses the collected data for various purposes:</p>
          <ul className="list-disc pl-6 mb-8 space-y-2">
            <li>To provide and maintain our Service</li>
            <li>To notify you about changes to our Service</li>
            <li>To provide customer support</li>
            <li>To gather analysis or valuable information so that we can improve our Service</li>
            <li>To monitor the usage of our Service</li>
            <li>To detect, prevent and address technical and security issues</li>
          </ul>

          <h2 className="text-2xl font-bold text-slate-900 mb-6 mt-10">5. Security of Data</h2>
          <p className="mb-8">
            The security of your data is important to us, but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.
          </p>

          <h2 className="text-2xl font-bold text-slate-900 mb-6 mt-10">6. Contact Us</h2>
          <p className="mb-4">If you have any questions about this Privacy Policy, please contact us at:</p>
          <p className="font-semibold">PickAll Movers</p>
          <p>Email: {import.meta.env.VITE_ADMIN_EMAIL || "support@pickall.in"}</p>
          <p className="text-sm text-slate-600 mt-8">Last updated: March 9, 2024</p>
        </div>
      </section>
    </div>
  );
}
